# Custom Language File for Launcher Customizer

[ejs.app]
title = "물초코"

[ejs.landing]
mediaGitHubURL = "https://bj.afreecatv.com/moolchoco"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaAfreecaTVURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/moolchoco"
supportLink = "https://github.com/CustomLauncherLab/moolchoco/issues"

[ejs.welcome]
welcomeHeader = "물초코"
welcomeDescription = ""
welcomeDescCTA = ""
